# vim: ft=yaml.ansible
---
- name: Configure host
  hosts: localhost
  tasks:
    - name: Apply role for each group
      ansible.builtin.include_role:
        name: "{{ role }}"
      loop: "{{ group_names }}"
      loop_control:
        loop_var: role
