---
- name: Configure desktops
  hosts: desktops
  roles:
    - desktop
- name: Configure laptops
  hosts: laptops
  roles:
    - laptop
- name: Configure hypervisors
  hosts: hypervisors
  roles:
    - hypervisor
- name: Configure virtual machines
  hosts: virtual_machines
  roles:
    - virtual_machine
- name: Configure cloud instances
  hosts: cloud_instances
  roles:
    - cloud_instance
- name: Configure unifi
  hosts: unifi
  roles:
    - unifi
