---
- name: Install desktop packages
  community.general.pacman:
    name:
      - bluez
      - bluez-utils
      - foot
      - git-crypt
      - libspnav
      - nvtop
      - rpi-imager
      - ttf-0xproto-nerd
      - usbutils
      - wl-clipboard
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Enable foot socket
  ansible.builtin.systemd_service:
    name: foot-server.socket
    enabled: true
    state: started
    scope: user

- name: Enable bluetooth service
  ansible.builtin.systemd_service:
    name: bluetooth
    enabled: true
    state: started
  become: true

- name: Set NetworkManager to use IPv6 temporary addresses by default
  ansible.builtin.copy:
    src: ip6-privacy.conf
    dest: /etc/NetworkManager/conf.d/ip6-privacy.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
