---
- name: Install desktop packages
  community.general.pacman:
    name:
      - bind
      - cowfortune
      - foot
      - foot-terminfo
      - fwupd
      - git-crypt
      - libfido2
      - libreoffice-still
      - libspnav
      - lolcat
      - man-db
      - man-pages
      - nvtop
      - rpi-imager
      - ttf-0xproto-nerd
      - usbutils
      - wl-clipboard
      - yubikey-manager
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Enable foot socket
  ansible.builtin.systemd_service:
    name: foot-server.socket
    enabled: true
    state: started
    scope: user

- name: Enable pcscd socket
  ansible.builtin.systemd_service:
    name: pcscd.socket
    enabled: true
    state: started
  become: true

- name: Ensure environment.d config directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}/.config/environment.d"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Set up SSH_AUTH_SOCK
  ansible.builtin.copy:
    src: ssh_auth_socket.conf
    dest: "{{ ansible_facts.user_dir }}/.config/environment.d/ssh_auth_socket.conf"
    mode: u=rw,g=r,o=r

- name: Enable ssh-agent
  ansible.builtin.systemd_service:
    name: ssh-agent
    enabled: true
    state: started
    scope: user
