---
- name: Install desktop packages
  community.general.pacman:
    name:
      - cowfortune
      - foot
      - foot-terminfo
      - fwupd
      - libreoffice-still
      - lolcat
      - man-db
      - man-pages
      - ttf-0xproto-nerd
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Enable foot socket
  ansible.builtin.systemd_service:
    name: foot-server.socket
    enabled: true
    state: started
    scope: user
