---
- name: Install ssh packages
  community.general.pacman:
    name:
      - openssh
      - gawk
      - rsync
      - ufw
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Create ssh group
  ansible.builtin.group:
    name: ssh
    state: present
  become: true
  notify: "Restart sshd"

- name: Add running user to ssh group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: ssh
    append: true
  become: true

- name: Create trusted user CA keys file
  ansible.builtin.assemble:
    src: files/pki/ssh/user_ca
    dest: /etc/ssh/trusted_user_ca_keys
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify: "Restart sshd"

- name: Create global known_hosts file
  ansible.builtin.template:
    src: templates/known_hosts.j2
    dest: /etc/ssh/ssh_known_hosts
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true

- name: Set up ssh config files
  ansible.posix.synchronize:
    src: config/
    dest: /etc/ssh/
    owner: false
    group: false
    times: false
    checksum: true
  become: true
  notify: "Restart sshd"

- name: Remove small Diffie-Hellman moduli
  ansible.builtin.shell: awk -i inplace '$5 >= 3071' /etc/ssh/moduli
  changed_when: true
  become: true

- name: Remove default ssh config on Arch Linux
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d/99-archlinux.conf
    state: absent
  become: true
  notify: "Restart sshd"

- name: Limit ssh access through firewall
  community.general.ufw:
    rule: limit
    name: SSH
  become: true

# Generate some keys so that sshd will start cleanly
# These will likely be regenerated later when creating host certificates
- name: Generate RSA key
  community.crypto.openssh_keypair:
    path: /etc/ssh/ssh_host_rsa_key
    size: 4096
    owner: root
    group: root
  become: true
  notify: "Restart sshd"

- name: Generate ED25519 key
  community.crypto.openssh_keypair:
    path: /etc/ssh/ssh_host_ed25519_key
    type: ed25519
    owner: root
    group: root
  become: true
  notify: "Restart sshd"

- name: Remove ECDSA key
  community.crypto.openssh_keypair:
    path: /etc/ssh/ssh_host_ecdsa_key
    state: absent
  become: true
  notify: "Restart sshd"

- name: Mask sshdgenkeys service
  ansible.builtin.systemd_service:
    name: sshdgenkeys
    masked: true
  become: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Start and enable sshd
  ansible.builtin.systemd_service:
    name: sshd
    state: started
    enabled: true
  become: true
  when: ansible_facts['distribution'] == "Archlinux"
