---
- name: Set systemd-boot loader.conf
  ansible.builtin.copy:
    src: loader.conf
    dest: /boot/loader/loader.conf
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Set /etc/kernel/cmdline
  ansible.builtin.copy:
    src: cmdline
    dest: /etc/kernel/cmdline
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify: "Regenerate initramfs"

- name: Set /etc/crypttab.initramfs
  ansible.builtin.copy:
    src: crypttab.initramfs
    dest: /etc/crypttab.initramfs
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify: "Regenerate initramfs"

- name: Use systemd mkinitcpio hooks
  ansible.builtin.copy:
    src: mkinitcpio-hooks.conf
    dest: /etc/mkinitcpio.conf.d/50-systemd-hooks.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify: "Regenerate initramfs"

- name: Enable systemd-boot-update
  ansible.builtin.systemd_service:
    name: systemd-boot-update
    enabled: true
  become: true
