---
- name: Set systemd-boot loader.conf
  ansible.builtin.copy:
    src: loader.conf
    dest: /boot/loader/loader.conf
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Enable systemd-boot-update
  ansible.builtin.systemd_service:
    name: systemd-boot-update
    enabled: true
  become: true
