---
- name: Install laptop packages
  community.general.pacman:
    name:
      - tlp
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Enable tlp
  ansible.builtin.systemd_service:
    name: tlp
    enabled: true
    state: started
  become: true

- name: Mask systemd-rfkill.service
  ansible.builtin.systemd_service:
    name: systemd-rfkill.service
    masked: true
  become: true

- name: Mask systemd-rfkill.socket
  ansible.builtin.systemd_service:
    name: systemd-rfkill.socket
    masked: true
  become: true
