---
- name: Install audio packages
  community.general.pacman:
    name:
      - pipewire
      - pipewire-alsa
      - pipewire-jack
      - pipewire-pulse
      - gst-plugin-pipewire
      - sof-firmware
      - wireplumber
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"
