---
- name: Install tailscale packages
  community.general.pacman:
    name:
      - tailscale
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Set up tailscale apt repository
  ansible.builtin.deb822_repository:
    name: tailscale
    types: deb
    uris: https://pkgs.tailscale.com/stable/ubuntu
    suites: "{{ ansible_distribution_release }}"
    components: main
    signed_by: https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.noarmor.gpg
    state: present
  become: true
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Install tailscale packages
  ansible.builtin.apt:
    name:
      - tailscale
      - tailscale-archive-keyring
    state: present
  become: true
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Enable tailscaled
  ansible.builtin.systemd_service:
    name: tailscaled
    enabled: true
    state: started
  become: true
