---
- name: Install fwupd packages
  community.general.pacman:
    name:
      - fwupd
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Ensure /etc/fwupd directory exists
  ansible.builtin.file:
    path: /etc/fwupd
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Disable fwupd p2p
  community.general.ini_file:
    path: /etc/fwupd/fwupd.conf
    section: fwupd
    option: P2pPolicy
    mode: u=rw,g=r
    value: nothing
    no_extra_spaces: true
  become: true

- name: Disable fwupd secure boot shim
  community.general.ini_file:
    path: /etc/fwupd/fwupd.conf
    section: uefi_capsule
    option: DisableShimForSecureBoot
    mode: u=rw,g=r
    value: true
    no_extra_spaces: true
  become: true

- name: Enable fwupd-refresh timer
  ansible.builtin.systemd_service:
    name: fwupd-refresh.timer
    enabled: true
    state: started
  become: true
