---
# This file exists on the ESP which is generally a FAT filesystem that doesn't
# support linux permissions or ownership. For that reason, not setting the user,
# group, or mode should be fine.
# noqa: risky-file-permissions
- name: Set systemd-boot loader.conf
  ansible.builtin.copy:
    src: loader.conf
    dest: /boot/loader/loader.conf
  become: true

- name: Enable systemd-boot-update
  ansible.builtin.systemd_service:
    name: systemd-boot-update
    enabled: true
  become: true
