---
- name: Install reflector packages
  community.general.pacman:
    name:
      - reflector
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Set up reflector config
  ansible.builtin.copy:
    src: reflector.conf
    dest: /etc/xdg/reflector/reflector.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  when: ansible_facts['distribution'] == "Archlinux"
  notify: "Run reflector"

- name: Enable reflector timer
  ansible.builtin.systemd_service:
    name: reflector.timer
    enabled: true
  become: true
  when: ansible_facts['distribution'] == "Archlinux"
