---
- name: Install yubikey packages
  community.general.pacman:
    name:
      - libfido2
      - yubikey-manager
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Enable pcscd socket
  ansible.builtin.systemd_service:
    name: pcscd.socket
    enabled: true
    state: started
  become: true
