---
- name: Install ansible packages
  community.general.pacman:
    name:
      - ansible
      - git
      - python
      - rsync
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Ensure /etc/ansible directory exists
  ansible.builtin.file:
    path: /etc/ansible
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Set default ansible.cfg file
  ansible.builtin.copy:
    src: ansible.cfg
    dest: /etc/ansible/ansible.cfg
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
