---
- name: Install terminal packages
  community.general.pacman:
    name:
      - atuin
      - bat
      - bat-extras
      - btop
      - chezmoi
      - cowfortune
      - direnv
      - duf
      - erdtree
      - eza
      - fd
      - fzf
      - git-delta
      - git-zsh-completion
      - github-cli
      - htop
      - lazygit
      - lolcat
      - pre-commit
      - prettier
      - ripgrep-all
      - starship
      - tldr
      - yazi
      - zoxide
      - zsh-autosuggestions
      - zsh-completions
      - zsh-history-substring-search
      - zsh-syntax-highlighting
      - rsync # for synchronize below
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Ensure bat theme directory exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(ansible_user_dir ~ '/.config', true) }}/bat/themes"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Set up bat themes
  ansible.builtin.synchronize:
    src: bat/
    dest: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(ansible_user_dir ~ '/.config', true) }}/bat/themes/"
    times: false
    checksum: true
  notify: "Rebuild bat cache"

- name: Ensure btop theme directory exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(ansible_user_dir ~ '/.config', true) }}/btop/themes"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Set up btop themes
  ansible.builtin.synchronize:
    src: btop/
    dest: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(ansible_user_dir ~ '/.config', true) }}/btop/themes/"
    times: false
    checksum: true
