---
- name: Install terminal packages
  community.general.pacman:
    name:
      - atuin
      - bat
      - bat-extras
      - bind
      - btop
      - chezmoi
      - cowfortune
      - curl
      - direnv
      - duf
      - erdtree
      - eza
      - fd
      - foot-terminfo
      - fzf
      - git
      - git-delta
      - git-zsh-completion
      - github-cli
      - go
      - htop
      - iperf3
      - jq
      - lazygit
      - less
      - lolcat
      - man-db
      - man-pages
      - pre-commit
      - prettier
      - python
      - python-pip
      - python-uv
      - ripgrep-all
      - rsync
      - rustup
      - starship
      - step-cli
      - tldr
      - unzip
      - wget
      - xh
      - yazi
      - zoxide
      - zsh
      - zsh-autosuggestions
      - zsh-completions
      - zsh-history-substring-search
      - zsh-syntax-highlighting
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Set running user's shell to zsh
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  become: true

- name: Ensure bat theme directory exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(ansible_user_dir ~ '/.config', true) }}/bat/themes"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Set up bat themes
  ansible.builtin.synchronize:
    src: bat/
    dest: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(ansible_user_dir ~ '/.config', true) }}/bat/themes/"
    times: false
    checksum: true
  notify: "Rebuild bat cache"

- name: Ensure btop theme directory exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(ansible_user_dir ~ '/.config', true) }}/btop/themes"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Set up btop themes
  ansible.builtin.synchronize:
    src: btop/
    dest: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(ansible_user_dir ~ '/.config', true) }}/btop/themes/"
    times: false
    checksum: true
