---
- name: Install terminal packages
  community.general.pacman:
    name:
      - aichat
      - atuin
      - bat
      - bat-extras
      - bind
      - btop
      - chezmoi
      - cowfortune
      - curl
      - direnv
      - duf
      - erdtree
      - eza
      - fd
      - foot-terminfo
      - fzf
      - git
      - git-delta
      - git-zsh-completion
      - github-cli
      - go
      - htop
      - iperf3
      - jq
      - lazygit
      - less
      - lolcat
      - man-db
      - man-pages
      - opencode
      - pre-commit
      - prettier
      - python
      - python-pip
      - python-uv
      - ripgrep-all
      - rsync
      - rustup
      - starship
      - tldr
      - unzip
      - wget
      - xh
      - yazi
      - yq
      - zoxide
      - zsh
      - zsh-autosuggestions
      - zsh-completions
      - zsh-history-substring-search
      - zsh-syntax-highlighting
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Set running user's shell to zsh
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    shell: /usr/bin/zsh
  become: true
