---
- name: Install terminal packages
  community.general.pacman:
    name:
      - chezmoi
      - fzf
      - zsh-completions
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"
