---
- name: Install common packages
  community.general.pacman:
    name:
      - ansible
      - curl
      - docker
      - docker-buildx
      - docker-compose
      - git
      - iperf3
      - less
      - neovim
      - python-pynvim
      - step-cli
      - tailscale
      - ufw
      - wget
      - zsh
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Set running user's shell to zsh
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  become: true

- name: Enable tailscaled
  ansible.builtin.systemd_service:
    name: tailscaled
    enabled: true
    state: started
  become: true
