---
- name: Install common packages
  community.general.pacman:
    name:
      - ansible
      - curl
      - docker
      - docker-buildx
      - docker-compose
      - git
      - go
      - iperf3
      - less
      - python
      - python-pip
      - rsync
      - step-cli
      - tailscale
      - ufw
      - unzip
      - wget
      - zsh
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Set running user's shell to zsh
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  become: true

- name: Enable systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    enabled: true
    state: started
  become: true

- name: Create systemd-resolved stub resolver symlink
  ansible.builtin.file:
    path: /etc/resolv.conf
    src: /run/systemd/resolve/stub-resolv.conf
    state: link
    follow: false
    force: true
  become: true

- name: Enable tailscaled
  ansible.builtin.systemd_service:
    name: tailscaled
    enabled: true
    state: started
  become: true

- name: Add root certs to system trust store
  ansible.posix.synchronize:
    src: pki/tls/
    dest: /etc/ca-certificates/trust-source/anchors/
    owner: false
    group: false
    delete: true
  become: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Update CA certs
  ansible.builtin.command: /usr/bin/update-ca-trust
  become: true
  when: ansible_facts['distribution'] == "Archlinux"
