---
- name: Install common packages
  community.general.pacman:
    name:
      - ansible
      - docker
      - docker-buildx
      - docker-compose
      - git
      - neovim
      - step-cli
      - tailscale
      - ufw
      - zsh
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"
