---
- name: Install common packages
  community.general.pacman:
    name:
      - bind
      - curl
      - foot-terminfo
      - git
      - go
      - iperf3
      - jq
      - less
      - man-db
      - man-pages
      - python
      - python-pip
      - python-uv
      - rsync
      - rustup
      - step-cli
      - unzip
      - wget
      - zsh
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Set running user's shell to zsh
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  become: true

- name: Add root certificates to system trust store
  ansible.posix.synchronize:
    src: pki/tls/
    dest: /etc/ca-certificates/trust-source/anchors/
    owner: false
    group: false
    delete: true
    times: false
    checksum: true
  become: true
  when: ansible_facts['distribution'] == "Archlinux"
  notify: "Update CA certificates"
