---
- name: Install common packages
  community.general.pacman:
    name:
      - ansible
      - bind
      - curl
      - foot-terminfo
      - git
      - go
      - iperf3
      - jq
      - less
      - man-db
      - man-pages
      - python
      - python-pip
      - python-uv
      - rsync
      - rustup
      - step-cli
      - unzip
      - wget
      - zsh
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Set running user's shell to zsh
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  become: true

- name: Enable systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    enabled: true
    state: started
  become: true

- name: Create systemd-resolved stub resolver symlink
  ansible.builtin.file:
    path: /etc/resolv.conf
    src: /run/systemd/resolve/stub-resolv.conf
    state: link
    follow: false
    force: true
  become: true

- name: Add root certificates to system trust store
  ansible.posix.synchronize:
    src: pki/tls/
    dest: /etc/ca-certificates/trust-source/anchors/
    owner: false
    group: false
    delete: true
    times: false
    checksum: true
  become: true
  when: ansible_facts['distribution'] == "Archlinux"
  notify: "Update CA certificates"

- name: Ensure /etc/ansible directory exists
  ansible.builtin.file:
    path: /etc/ansible
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Set default ansible.cfg file
  ansible.builtin.copy:
    src: ansible.cfg
    dest: /etc/ansible/ansible.cfg
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
