---
- name: Add root certificates to system trust store
  ansible.posix.synchronize:
    src: pki/tls/
    dest: /etc/ca-certificates/trust-source/anchors/
    owner: false
    group: false
    delete: true
    times: false
    checksum: true
  become: true
  when: ansible_facts['distribution'] == "Archlinux"
  notify: "Update CA certificates"
