- name: Install step packages
  community.general.pacman:
    name:
      - step-cli
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Set up smallstep apt repository
  ansible.builtin.deb822_repository:
    name: smallstep
    types: deb
    uris: https://packages.smallstep.com/stable/debian
    suites: debs
    components: main
    signed_by: https://packages.smallstep.com/keys/apt/repo-signing-key.gpg
    state: present
  become: true
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Install step packages
  ansible.builtin.apt:
    name:
      - step-cli
    state: present
  become: true
  when: ansible_facts['distribution'] == "Ubuntu"
