---
name: Release

on:
  push:
    branches:
      - main
    paths:
      - install.sh
      - roles/ansible/files/system-setup

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Calver
        uses: energostack/calver-action@v1
        id: calver
        with:
          date_format: "%Y.%-m"

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.calver.outputs.next_version }}
          name: "Version ${{ steps.calver.outputs.next_version }}"
          files: |
            install.sh
            roles/ansible/files/system-setup
